
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 15 08:49:23 CST 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LEFTBRACKET = 34;
  public static final int READLINE = 23;
  public static final int MULT = 48;
  public static final int CONST = 54;
  public static final int EQUALS = 31;
  public static final int RIGHTBRACKET = 35;
  public static final int DOUBLE = 3;
  public static final int GTREQ = 41;
  public static final int INTERFACE = 8;
  public static final int INT = 2;
  public static final int MINUS = 47;
  public static final int FOR = 13;
  public static final int STRINGCONST = 59;
  public static final int AND = 44;
  public static final int READINTEGER = 22;
  public static final int INTCONST = 56;
  public static final int OR = 45;
  public static final int COMMA = 50;
  public static final int BOOL = 5;
  public static final int DOUBLECONST = 57;
  public static final int CLASS = 7;
  public static final int DIV = 43;
  public static final int DIFFERENT = 42;
  public static final int NEWARRAY = 20;
  public static final int LESSEQ = 40;
  public static final int IF = 15;
  public static final int GETBYTE = 52;
  public static final int THIS = 10;
  public static final int DOT = 49;
  public static final int SETBYTE = 53;
  public static final int EOF = 0;
  public static final int RETURN = 17;
  public static final int TRUE = 60;
  public static final int RIGHTCURLY = 39;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int PERCENT = 28;
  public static final int ADD = 46;
  public static final int NULL = 9;
  public static final int BREAK = 18;
  public static final int VOID = 4;
  public static final int ERROR = 55;
  public static final int LEFTCURLY = 38;
  public static final int TWOPAR = 27;
  public static final int RIGHTPAR = 37;
  public static final int GREATT = 30;
  public static final int ELSE = 16;
  public static final int WHILE = 14;
  public static final int LEFTPAR = 36;
  public static final int PAC = 33;
  public static final int EXTENDS = 11;
  public static final int STRING = 6;
  public static final int MALLOC = 24;
  public static final int TWOCURLY = 26;
  public static final int FALSE = 61;
  public static final int COMPEQUALS = 51;
  public static final int LESST = 29;
  public static final int IMPLEMENTS = 12;
  public static final int PRINT = 21;
  public static final int TWOBRACK = 25;
  public static final int IDENTIFIER = 58;
  public static final int EXCLA = 32;
}

