/* The following code was generated by JFlex 1.6.1 */

package Lexical;

import java.io.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/Lexical/lexer.flex</tt>
 */
public class Yylex {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\2\1\4\1\10\1\11\1\3\22\0\1\5\1\54\1\6"+
    "\2\0\1\1\1\55\1\0\1\64\1\65\1\12\1\66\1\74\1\67"+
    "\1\70\1\7\1\14\1\75\1\76\1\75\6\21\1\0\1\1\1\52"+
    "\1\53\1\54\2\0\1\50\3\20\1\71\1\20\7\72\1\47\11\72"+
    "\1\17\2\72\1\60\1\57\1\61\1\0\1\73\1\0\1\40\1\30"+
    "\1\37\1\25\1\32\1\41\1\36\1\42\1\22\1\72\1\46\1\31"+
    "\1\43\1\23\1\26\1\44\1\72\1\35\1\34\1\24\1\27\1\33"+
    "\1\45\1\15\1\51\1\72\1\62\1\56\1\63\7\0\1\10\u1f96\0"+
    "\1\13\1\16\12\0\1\10\1\10\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\3\1\1\1\2\1\4\1\1"+
    "\1\5\1\1\1\5\15\1\2\2\3\1\1\6\1\7"+
    "\1\2\1\10\1\0\1\11\1\12\2\0\2\10\2\0"+
    "\1\13\1\0\2\13\1\0\1\14\20\0\1\15\1\16"+
    "\1\17\10\0\1\20\1\21\2\0\1\13\1\22\1\0"+
    "\1\13\1\23\2\14\14\0\1\24\2\0\1\25\1\26"+
    "\1\27\1\30\4\0\1\31\1\20\1\10\1\22\2\23"+
    "\2\0\1\32\1\33\1\34\4\0\1\35\3\0\2\24"+
    "\2\0\2\25\2\0\1\31\1\21\3\0\2\32\2\34"+
    "\1\0\1\36\3\0\1\13\2\35\2\0\1\37\1\40"+
    "\1\41\1\0\1\31\1\21\2\0\1\42\2\36\2\0"+
    "\1\43\1\0\2\37\2\41\3\0\2\42\1\44\1\0"+
    "\2\43\2\0\1\13\3\0\2\44\3\0\1\45\1\0"+
    "\1\46\3\0\1\13\2\45\1\47\2\0\2\47\4\0"+
    "\1\50\4\0\1\51";

  private static int [] zzUnpackAction() {
    int [] result = new int[219];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\77\0\77\0\77\0\176\0\275\0\374\0\77"+
    "\0\u013b\0\u017a\0\u01b9\0\u01f8\0\u0237\0\u0276\0\u02b5\0\u02f4"+
    "\0\u0333\0\u0372\0\u03b1\0\u03f0\0\u042f\0\u046e\0\u04ad\0\u04ec"+
    "\0\u052b\0\u056a\0\u05a9\0\u05e8\0\u0627\0\u0666\0\77\0\77"+
    "\0\u06a5\0\u06a5\0\275\0\275\0\u06e4\0\u0723\0\u0762\0\u07a1"+
    "\0\u07e0\0\u081f\0\u085e\0\u081f\0\u089d\0\77\0\u089d\0\u08dc"+
    "\0\u091b\0\u095a\0\u0999\0\u09d8\0\u0a17\0\u0a56\0\u0a95\0\u0ad4"+
    "\0\u0b13\0\u0b52\0\u0b91\0\u0bd0\0\u0c0f\0\u0c4e\0\u0c8d\0\u0ccc"+
    "\0\u0d0b\0\77\0\77\0\77\0\u0d4a\0\u0d89\0\u0dc8\0\u0e07"+
    "\0\u0e46\0\u0e85\0\u0ec4\0\u0f03\0\u07a1\0\u0f42\0\u0f81\0\u0fc0"+
    "\0\u0f81\0\u0fff\0\u0fff\0\u0fff\0\u103e\0\u0f81\0\u107d\0\u10bc"+
    "\0\u10fb\0\u113a\0\u1179\0\u11b8\0\u11f7\0\u1236\0\u1275\0\u12b4"+
    "\0\u12f3\0\u1332\0\u1371\0\u13b0\0\u13ef\0\u142e\0\u146d\0\77"+
    "\0\77\0\77\0\u14ac\0\u14eb\0\u152a\0\u1569\0\u0e07\0\77"+
    "\0\u15a8\0\77\0\u081f\0\u15e7\0\u1626\0\u1665\0\u16a4\0\u0fff"+
    "\0\u16e3\0\u1722\0\u1761\0\u17a0\0\u17df\0\u181e\0\u185d\0\u189c"+
    "\0\u18db\0\u081f\0\u191a\0\u1959\0\u1998\0\u081f\0\u19d7\0\u1a16"+
    "\0\u1a55\0\u0e85\0\u1a94\0\u1ad3\0\u1b12\0\u1b51\0\u081f\0\u1b90"+
    "\0\u081f\0\u1bcf\0\u1c0e\0\u1c4d\0\u1c8c\0\u1ccb\0\u1d0a\0\u1ccb"+
    "\0\u081f\0\u1d49\0\u1d88\0\u1dc7\0\u1e06\0\u0fff\0\u1e45\0\u1e84"+
    "\0\77\0\u1ad3\0\u1ec3\0\u1f02\0\u1f41\0\u081f\0\u1f80\0\u1fbf"+
    "\0\u1ffe\0\u203d\0\u207c\0\u081f\0\u20bb\0\u081f\0\u20fa\0\u2139"+
    "\0\u2178\0\u21b7\0\u081f\0\u21f6\0\u2235\0\u2274\0\u081f\0\u22b3"+
    "\0\u22f2\0\u2331\0\u22f2\0\u2370\0\u23af\0\u23ee\0\u081f\0\u242d"+
    "\0\u246c\0\u24ab\0\u24ea\0\u2529\0\u2568\0\77\0\u25a7\0\u25e6"+
    "\0\u2625\0\u25e6\0\u081f\0\u2664\0\u26a3\0\u26e2\0\u2721\0\u081f"+
    "\0\u2760\0\u279f\0\u27de\0\u281d\0\u285c\0\77\0\u289b\0\u28da"+
    "\0\u2919\0\u2958\0\77";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[219];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\2\4\1\6\1\7\1\0"+
    "\1\4\1\10\1\11\1\12\1\13\1\2\2\13\1\14"+
    "\1\15\1\16\1\17\1\20\2\13\1\21\1\13\1\22"+
    "\1\23\1\24\1\25\1\13\1\26\1\13\1\27\3\13"+
    "\1\30\1\13\1\31\2\13\1\32\1\3\1\33\1\34"+
    "\1\35\1\36\6\3\1\37\1\40\1\41\2\13\1\42"+
    "\1\3\2\14\103\0\1\4\72\0\3\43\2\0\1\43"+
    "\1\44\1\43\2\0\65\43\7\0\1\45\2\0\1\46"+
    "\100\0\1\47\76\0\1\14\1\42\1\0\1\50\1\42"+
    "\1\14\30\42\16\0\1\51\3\42\1\0\2\14\2\0"+
    "\1\52\1\53\1\52\1\54\3\0\1\52\2\0\2\55"+
    "\1\0\33\55\17\0\3\55\1\56\1\57\1\55\14\0"+
    "\1\14\1\42\1\0\2\42\1\14\30\42\16\0\1\51"+
    "\3\42\1\0\2\14\2\0\1\52\1\53\1\52\1\54"+
    "\3\0\1\52\2\0\2\55\1\0\4\55\1\60\15\55"+
    "\1\61\1\55\1\62\6\55\17\0\3\55\1\56\1\57"+
    "\1\55\2\0\1\52\1\53\1\52\1\54\3\0\1\52"+
    "\2\0\2\55\1\0\10\55\1\63\22\55\17\0\3\55"+
    "\1\56\1\57\1\55\2\0\1\52\1\53\1\52\1\54"+
    "\3\0\1\52\2\0\2\55\1\0\16\55\1\64\4\55"+
    "\1\65\7\55\17\0\3\55\1\56\1\57\1\55\2\0"+
    "\1\52\1\53\1\52\1\54\3\0\1\52\2\0\2\55"+
    "\1\0\7\55\1\66\23\55\17\0\3\55\1\56\1\57"+
    "\1\55\2\0\1\52\1\53\1\52\1\54\3\0\1\52"+
    "\2\0\2\55\1\0\16\55\1\67\14\55\17\0\3\55"+
    "\1\56\1\57\1\55\2\0\1\52\1\53\1\52\1\54"+
    "\3\0\1\52\2\0\1\55\1\70\1\0\12\55\1\71"+
    "\20\55\17\0\3\55\1\56\1\57\1\55\2\0\1\52"+
    "\1\53\1\52\1\54\3\0\1\52\2\0\2\55\1\0"+
    "\7\55\1\72\23\55\17\0\3\55\1\56\1\57\1\55"+
    "\2\0\1\52\1\53\1\52\1\54\3\0\1\52\2\0"+
    "\2\55\1\0\5\55\1\73\25\55\17\0\3\55\1\56"+
    "\1\57\1\55\2\0\1\52\1\53\1\52\1\54\3\0"+
    "\1\52\2\0\2\55\1\0\13\55\1\74\17\55\17\0"+
    "\3\55\1\56\1\57\1\55\2\0\1\52\1\53\1\52"+
    "\1\54\3\0\1\52\2\0\2\55\1\0\12\55\1\75"+
    "\20\55\17\0\3\55\1\56\1\57\1\55\2\0\1\52"+
    "\1\53\1\52\1\54\3\0\1\52\2\0\2\55\1\0"+
    "\7\55\1\76\11\55\1\77\11\55\17\0\3\55\1\56"+
    "\1\57\1\55\2\0\1\52\1\53\1\52\1\54\3\0"+
    "\1\52\2\0\2\55\1\0\23\55\1\100\7\55\17\0"+
    "\3\55\1\56\1\57\1\55\2\0\1\52\1\53\1\52"+
    "\1\54\3\0\1\52\2\0\2\55\1\0\13\55\1\101"+
    "\17\55\17\0\3\55\1\56\1\57\1\55\53\0\1\102"+
    "\76\0\1\103\100\0\1\103\77\0\1\104\100\0\1\105"+
    "\1\0\1\106\1\0\1\107\26\0\2\42\1\0\33\42"+
    "\16\0\4\42\1\0\2\42\3\45\2\0\3\45\2\0"+
    "\65\45\2\110\2\111\1\112\1\111\2\110\1\0\1\111"+
    "\1\113\64\110\15\0\1\114\75\0\1\115\1\42\1\0"+
    "\1\42\2\115\3\42\1\115\2\42\1\115\1\42\1\115"+
    "\4\42\3\115\6\42\1\115\1\42\16\0\1\42\1\115"+
    "\2\42\1\0\2\115\14\0\1\116\1\42\1\0\2\42"+
    "\1\116\30\42\16\0\4\42\1\0\2\116\5\0\1\56"+
    "\66\0\2\56\5\0\1\52\1\56\66\0\2\56\3\0"+
    "\1\117\1\120\1\117\1\121\3\0\1\117\2\0\1\122"+
    "\1\123\1\0\33\123\17\0\3\123\1\56\1\124\1\122"+
    "\2\0\1\117\1\120\1\117\1\121\3\0\1\117\2\0"+
    "\1\122\1\123\1\0\5\123\1\125\25\123\17\0\3\123"+
    "\1\56\1\124\1\122\2\0\1\126\1\127\2\126\3\0"+
    "\1\126\2\0\1\122\1\123\1\0\33\123\17\0\3\123"+
    "\1\56\1\124\1\122\2\0\1\117\1\120\1\117\1\121"+
    "\3\0\1\117\2\0\1\122\1\123\1\0\25\123\1\130"+
    "\5\123\17\0\3\123\1\56\1\124\1\122\2\0\1\117"+
    "\1\120\1\117\1\121\3\0\1\117\2\0\1\122\1\123"+
    "\1\0\12\123\1\131\20\123\17\0\3\123\1\56\1\124"+
    "\1\122\2\0\1\117\1\120\1\117\1\121\3\0\1\117"+
    "\2\0\1\122\1\123\1\0\10\123\1\132\22\123\17\0"+
    "\3\123\1\56\1\124\1\122\2\0\1\117\1\120\1\117"+
    "\1\121\3\0\1\117\2\0\1\122\1\123\1\0\3\123"+
    "\1\133\27\123\17\0\3\123\1\56\1\124\1\122\2\0"+
    "\1\117\1\120\1\117\1\121\3\0\1\117\2\0\1\122"+
    "\1\123\1\0\10\123\1\134\22\123\17\0\3\123\1\56"+
    "\1\124\1\122\2\0\1\117\1\120\1\117\1\121\3\0"+
    "\1\117\2\0\1\122\1\123\1\0\13\123\1\135\17\123"+
    "\17\0\3\123\1\56\1\124\1\122\2\0\1\117\1\120"+
    "\1\117\1\121\3\0\1\117\2\0\1\122\1\123\1\0"+
    "\5\123\1\136\25\123\17\0\3\123\1\56\1\124\1\122"+
    "\2\0\1\117\1\120\1\117\1\121\3\0\1\117\2\0"+
    "\1\122\1\123\1\0\15\123\1\137\15\123\17\0\3\123"+
    "\1\56\1\124\1\122\2\0\1\117\1\120\1\117\1\121"+
    "\3\0\1\117\2\0\1\122\1\123\1\0\3\123\1\140"+
    "\27\123\17\0\3\123\1\56\1\124\1\122\2\0\1\117"+
    "\1\120\1\117\1\121\3\0\1\117\2\0\1\122\1\123"+
    "\1\0\16\123\1\141\14\123\17\0\3\123\1\56\1\124"+
    "\1\122\2\0\1\117\1\120\1\117\1\121\3\0\1\117"+
    "\2\0\1\122\1\123\1\0\5\123\1\142\25\123\17\0"+
    "\3\123\1\56\1\124\1\122\2\0\1\117\1\120\1\117"+
    "\1\121\3\0\1\117\2\0\1\122\1\123\1\0\21\123"+
    "\1\143\11\123\17\0\3\123\1\56\1\124\1\122\2\0"+
    "\1\117\1\120\1\117\1\121\3\0\1\117\2\0\1\122"+
    "\1\123\1\0\16\123\1\144\14\123\17\0\3\123\1\56"+
    "\1\124\1\122\2\0\1\117\1\120\1\117\1\121\3\0"+
    "\1\117\2\0\1\122\1\123\1\0\12\123\1\145\20\123"+
    "\17\0\3\123\1\56\1\124\1\122\2\0\1\117\1\120"+
    "\1\117\1\121\3\0\1\117\2\0\1\122\1\123\1\0"+
    "\3\123\1\146\27\123\17\0\3\123\1\56\1\124\1\122"+
    "\2\0\1\117\1\120\1\117\1\121\3\0\1\117\2\0"+
    "\1\122\1\123\1\0\26\123\1\147\4\123\17\0\3\123"+
    "\1\56\1\124\1\122\61\0\1\150\100\0\1\151\100\0"+
    "\1\152\11\0\3\110\1\0\1\112\3\110\2\0\67\110"+
    "\1\153\1\154\1\112\1\153\2\110\1\0\1\155\1\113"+
    "\64\110\3\112\1\154\4\112\1\0\1\155\1\156\64\112"+
    "\3\110\1\0\1\112\2\110\1\157\2\0\65\110\16\0"+
    "\1\160\74\0\1\116\1\42\1\0\2\42\1\116\10\42"+
    "\1\161\17\42\16\0\1\42\1\161\2\42\1\0\2\116"+
    "\5\0\1\56\6\0\1\162\57\0\2\56\1\162\4\0"+
    "\1\117\1\56\6\0\1\162\57\0\2\56\1\162\2\0"+
    "\1\52\1\53\1\52\1\54\3\0\1\52\2\0\2\123"+
    "\1\0\33\123\17\0\3\123\1\56\1\124\1\123\2\0"+
    "\1\163\1\164\2\163\3\0\1\163\2\0\2\123\1\0"+
    "\13\123\1\165\17\123\17\0\3\123\1\56\1\124\1\123"+
    "\4\0\1\126\1\56\6\0\1\162\57\0\2\56\1\162"+
    "\2\0\1\52\1\53\1\52\1\54\3\0\1\52\2\0"+
    "\2\123\1\0\12\123\1\166\20\123\17\0\3\123\1\56"+
    "\1\124\1\123\2\0\1\52\1\53\1\52\1\54\3\0"+
    "\1\52\2\0\2\123\1\0\12\123\1\167\20\123\17\0"+
    "\3\123\1\56\1\124\1\123\2\0\1\52\1\53\1\52"+
    "\1\54\3\0\1\52\2\0\2\123\1\0\13\123\1\170"+
    "\17\123\17\0\3\123\1\56\1\124\1\123\2\0\1\52"+
    "\1\53\1\52\1\54\3\0\1\52\2\0\2\123\1\0"+
    "\15\123\1\171\15\123\17\0\3\123\1\56\1\124\1\123"+
    "\2\0\1\52\1\53\1\52\1\54\3\0\1\52\2\0"+
    "\2\123\1\0\11\123\1\172\21\123\17\0\3\123\1\56"+
    "\1\124\1\123\2\0\1\52\1\53\1\52\1\54\3\0"+
    "\1\52\2\0\2\123\1\0\21\123\1\173\11\123\17\0"+
    "\3\123\1\56\1\124\1\123\2\0\1\52\1\53\1\52"+
    "\1\54\3\0\1\52\2\0\2\123\1\0\13\123\1\174"+
    "\17\123\17\0\3\123\1\56\1\124\1\123\2\0\1\52"+
    "\1\53\1\52\1\54\3\0\1\52\2\0\2\123\1\0"+
    "\13\123\1\175\17\123\17\0\3\123\1\56\1\124\1\123"+
    "\2\0\1\52\1\53\1\52\1\54\3\0\1\52\2\0"+
    "\2\123\1\0\6\123\1\176\24\123\17\0\3\123\1\56"+
    "\1\124\1\123\2\0\1\52\1\53\1\52\1\54\3\0"+
    "\1\52\2\0\2\123\1\0\3\123\1\177\27\123\17\0"+
    "\3\123\1\56\1\124\1\123\2\0\1\52\1\53\1\52"+
    "\1\54\3\0\1\52\2\0\2\123\1\0\10\123\1\200"+
    "\22\123\17\0\3\123\1\56\1\124\1\123\2\0\1\52"+
    "\1\53\1\52\1\54\3\0\1\52\2\0\2\123\1\0"+
    "\15\123\1\201\15\123\17\0\3\123\1\56\1\124\1\123"+
    "\2\0\1\202\1\203\2\202\3\0\1\202\2\0\2\123"+
    "\1\0\33\123\17\0\3\123\1\56\1\124\1\123\2\0"+
    "\1\52\1\53\1\52\1\54\3\0\1\52\2\0\2\123"+
    "\1\0\15\123\1\204\15\123\17\0\3\123\1\56\1\124"+
    "\1\123\2\0\1\52\1\53\1\52\1\54\3\0\1\52"+
    "\2\0\2\123\1\0\12\123\1\205\20\123\17\0\3\123"+
    "\1\56\1\124\1\123\2\0\1\206\1\207\2\206\3\0"+
    "\1\206\2\0\2\123\1\0\31\123\1\210\1\123\17\0"+
    "\3\123\1\56\1\124\1\123\3\110\1\0\1\112\3\110"+
    "\2\0\1\113\64\110\4\0\1\155\5\0\1\211\76\0"+
    "\1\211\64\0\3\112\1\154\3\112\1\212\1\0\1\155"+
    "\1\156\64\112\14\0\1\213\1\42\1\0\2\42\1\213"+
    "\30\42\14\0\2\214\4\42\1\0\2\213\4\0\1\163"+
    "\1\56\66\0\2\56\3\0\1\52\1\53\1\52\1\54"+
    "\3\0\1\52\2\0\2\123\1\0\16\123\1\215\14\123"+
    "\17\0\3\123\1\56\1\124\1\123\2\0\1\52\1\53"+
    "\1\52\1\54\3\0\1\52\2\0\2\123\1\0\13\123"+
    "\1\216\17\123\17\0\3\123\1\56\1\124\1\123\2\0"+
    "\1\217\1\220\2\217\3\0\1\217\2\0\2\123\1\0"+
    "\33\123\17\0\3\123\1\56\1\124\1\123\2\0\1\221"+
    "\1\222\2\221\3\0\1\221\2\0\2\123\1\0\33\123"+
    "\17\0\3\123\1\56\1\124\1\123\2\0\1\52\1\53"+
    "\1\52\1\54\3\0\1\52\2\0\2\123\1\0\12\123"+
    "\1\223\20\123\17\0\3\123\1\56\1\124\1\123\2\0"+
    "\1\52\1\53\1\52\1\54\3\0\1\52\2\0\2\123"+
    "\1\0\27\123\1\224\3\123\17\0\3\123\1\56\1\124"+
    "\1\123\2\0\1\52\1\53\1\52\1\54\3\0\1\52"+
    "\2\0\2\123\1\0\4\123\1\225\26\123\17\0\3\123"+
    "\1\56\1\124\1\123\2\0\1\226\1\227\1\226\1\230"+
    "\3\0\1\226\2\0\2\123\1\0\33\123\17\0\3\123"+
    "\1\56\1\124\1\123\2\0\1\231\1\232\2\231\3\0"+
    "\1\231\2\0\2\123\1\0\33\123\17\0\3\123\1\56"+
    "\1\124\1\123\2\0\1\52\1\53\1\52\1\54\3\0"+
    "\1\52\2\0\2\123\1\0\4\123\1\233\26\123\17\0"+
    "\3\123\1\56\1\124\1\123\2\0\1\52\1\53\1\52"+
    "\1\54\3\0\1\52\2\0\2\123\1\0\16\123\1\234"+
    "\14\123\17\0\3\123\1\56\1\124\1\123\2\0\1\52"+
    "\1\53\1\52\1\54\3\0\1\52\2\0\2\123\1\0"+
    "\15\123\1\235\15\123\17\0\3\123\1\56\1\124\1\123"+
    "\4\0\1\202\1\56\66\0\2\56\3\0\1\52\1\53"+
    "\1\52\1\54\3\0\1\52\2\0\2\123\1\0\13\123"+
    "\1\236\17\123\17\0\3\123\1\56\1\124\1\123\2\0"+
    "\1\52\1\53\1\52\1\54\3\0\1\52\2\0\2\123"+
    "\1\0\13\123\1\237\17\123\17\0\3\123\1\56\1\124"+
    "\1\123\4\0\1\206\1\56\66\0\2\56\3\0\1\52"+
    "\1\53\1\52\1\54\3\0\1\52\2\0\2\123\1\0"+
    "\16\123\1\240\14\123\17\0\3\123\1\56\1\124\1\123"+
    "\7\0\1\241\103\0\1\213\1\42\1\0\2\42\1\213"+
    "\30\42\16\0\4\42\1\0\2\213\14\0\1\242\4\0"+
    "\1\242\53\0\2\242\2\0\1\52\1\53\1\52\1\54"+
    "\3\0\1\52\2\0\2\123\1\0\22\123\1\243\10\123"+
    "\17\0\3\123\1\56\1\124\1\123\2\0\1\52\1\53"+
    "\1\52\1\54\3\0\1\52\2\0\2\123\1\0\24\123"+
    "\1\244\6\123\17\0\3\123\1\56\1\124\1\123\4\0"+
    "\1\217\1\56\66\0\2\56\5\0\1\221\1\56\66\0"+
    "\2\56\3\0\1\52\1\53\1\52\1\54\3\0\1\52"+
    "\2\0\2\123\1\0\13\123\1\245\17\123\17\0\3\123"+
    "\1\56\1\124\1\123\2\0\1\246\1\247\2\246\3\0"+
    "\1\246\2\0\2\123\1\0\33\123\17\0\3\123\1\56"+
    "\1\124\1\123\2\0\1\52\1\53\1\52\1\54\3\0"+
    "\1\52\2\0\2\123\1\0\6\123\1\250\24\123\17\0"+
    "\3\123\1\56\1\124\1\123\5\0\1\56\24\0\1\251"+
    "\41\0\2\56\5\0\1\226\1\56\24\0\1\251\41\0"+
    "\2\56\5\0\1\231\1\56\66\0\2\56\3\0\1\52"+
    "\1\53\1\52\1\54\3\0\1\52\2\0\2\123\1\0"+
    "\17\123\1\252\13\123\17\0\3\123\1\56\1\124\1\123"+
    "\2\0\1\52\1\53\1\52\1\54\3\0\1\52\2\0"+
    "\2\123\1\0\4\123\1\253\26\123\17\0\3\123\1\56"+
    "\1\124\1\123\2\0\1\254\1\255\2\254\3\0\1\254"+
    "\2\0\2\123\1\0\33\123\17\0\3\123\1\56\1\124"+
    "\1\123\2\0\1\256\1\257\2\256\3\0\1\256\2\0"+
    "\2\123\1\0\33\123\17\0\3\123\1\56\1\124\1\123"+
    "\2\0\1\52\1\53\1\52\1\54\3\0\1\52\2\0"+
    "\2\123\1\0\16\123\1\260\14\123\17\0\3\123\1\56"+
    "\1\124\1\123\2\0\1\52\1\53\1\52\1\54\3\0"+
    "\1\52\2\0\2\123\1\0\21\123\1\261\11\123\17\0"+
    "\3\123\1\56\1\124\1\123\2\0\1\52\1\53\1\52"+
    "\1\54\3\0\1\52\2\0\2\123\1\0\13\123\1\262"+
    "\17\123\17\0\3\123\1\56\1\124\1\123\2\0\1\263"+
    "\1\264\2\263\3\0\1\263\2\0\2\123\1\0\33\123"+
    "\17\0\3\123\1\56\1\124\1\123\4\0\1\246\1\56"+
    "\66\0\2\56\3\0\1\52\1\53\1\52\1\54\3\0"+
    "\1\52\2\0\2\123\1\0\15\123\1\265\15\123\17\0"+
    "\3\123\1\56\1\124\1\123\31\0\1\266\47\0\1\267"+
    "\1\270\2\267\3\0\1\267\2\0\2\123\1\0\33\123"+
    "\17\0\3\123\1\56\1\124\1\123\2\0\1\271\1\272"+
    "\1\271\1\273\3\0\1\271\2\0\2\123\1\0\33\123"+
    "\17\0\3\123\1\56\1\124\1\123\4\0\1\254\1\56"+
    "\66\0\2\56\5\0\1\256\1\56\66\0\2\56\3\0"+
    "\1\52\1\53\1\52\1\54\3\0\1\52\2\0\2\123"+
    "\1\0\21\123\1\274\11\123\17\0\3\123\1\56\1\124"+
    "\1\123\2\0\1\52\1\53\1\52\1\54\3\0\1\52"+
    "\2\0\2\123\1\0\20\123\1\275\12\123\17\0\3\123"+
    "\1\56\1\124\1\123\2\0\1\52\1\53\1\52\1\54"+
    "\3\0\1\52\2\0\2\123\1\0\4\123\1\276\26\123"+
    "\17\0\3\123\1\56\1\124\1\123\4\0\1\263\1\56"+
    "\66\0\2\56\3\0\1\277\1\300\2\277\3\0\1\277"+
    "\2\0\2\123\1\0\33\123\17\0\3\123\1\56\1\124"+
    "\1\123\34\0\1\301\46\0\1\267\1\56\66\0\2\56"+
    "\6\0\1\56\27\0\1\302\36\0\2\56\5\0\1\271"+
    "\1\56\27\0\1\302\36\0\2\56\3\0\1\52\1\53"+
    "\1\52\1\54\3\0\1\52\2\0\2\123\1\0\32\123"+
    "\1\303\17\0\3\123\1\56\1\124\1\123\2\0\1\52"+
    "\1\53\1\52\1\54\3\0\1\52\2\0\2\123\1\0"+
    "\13\123\1\304\17\123\17\0\3\123\1\56\1\124\1\123"+
    "\2\0\1\52\1\53\1\52\1\54\3\0\1\52\2\0"+
    "\2\123\1\0\5\123\1\305\25\123\17\0\3\123\1\56"+
    "\1\124\1\123\4\0\1\277\1\56\66\0\2\56\33\0"+
    "\1\306\76\0\1\307\46\0\1\310\1\311\1\310\1\312"+
    "\3\0\1\310\2\0\2\123\1\0\33\123\17\0\3\123"+
    "\1\56\1\124\1\123\2\0\1\313\1\314\2\313\3\0"+
    "\1\313\2\0\2\123\1\0\33\123\17\0\3\123\1\56"+
    "\1\124\1\123\2\0\1\52\1\53\1\52\1\54\3\0"+
    "\1\52\2\0\2\123\1\0\15\123\1\315\15\123\17\0"+
    "\3\123\1\56\1\124\1\123\24\0\1\316\57\0\1\56"+
    "\41\0\1\317\24\0\2\56\5\0\1\310\1\56\41\0"+
    "\1\317\24\0\2\56\5\0\1\313\1\56\66\0\2\56"+
    "\3\0\1\320\1\321\2\320\3\0\1\320\2\0\2\123"+
    "\1\0\33\123\17\0\3\123\1\56\1\124\1\123\27\0"+
    "\1\322\101\0\1\323\50\0\1\320\1\56\66\0\2\56"+
    "\36\0\1\324\106\0\1\325\54\0\1\326\123\0\1\327"+
    "\63\0\1\330\76\0\1\331\101\0\1\332\107\0\1\333"+
    "\25\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[10647];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\3\11\3\1\1\11\26\1\2\11\2\1\1\0"+
    "\2\1\2\0\2\1\2\0\1\1\1\0\1\11\1\1"+
    "\1\0\1\1\20\0\3\11\10\0\2\1\2\0\2\1"+
    "\1\0\4\1\14\0\1\1\2\0\1\1\3\11\4\0"+
    "\1\1\1\11\1\1\1\11\2\1\2\0\3\1\4\0"+
    "\1\1\3\0\2\1\2\0\2\1\2\0\2\1\3\0"+
    "\4\1\1\0\1\1\3\0\3\1\2\0\3\1\1\0"+
    "\1\11\1\1\2\0\3\1\2\0\1\1\1\0\4\1"+
    "\3\0\3\1\1\0\2\1\2\0\1\1\3\0\2\1"+
    "\3\0\1\1\1\0\1\11\3\0\4\1\2\0\2\1"+
    "\4\0\1\11\4\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[219];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    String token = "";
    int fixed = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 204) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public String yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return "Token no reconocido: " + yytext() + " en linea: " + yyline+ " columna " + yycolumn;
            }
          case 42: break;
          case 2: 
            { token = yytext();
    return yytext() + " line " + yyline + " cols " + yycolumn + " is " + "'" + token + "'";
            }
          case 43: break;
          case 3: 
            { // accion vacia: se ignoran los espacios y tabuladores
            }
          case 44: break;
          case 4: 
            { return yytext() + " line " + yyline + " cols " + yycolumn + " is " + "'*'";
            }
          case 45: break;
          case 5: 
            { token = yytext();
    fixed = token.length() - 1;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed +  " is intConstant  " + "(value = " + token + ")";
            }
          case 46: break;
          case 6: 
            { return yytext() + " line " + yyline + " cols " + yycolumn + " is " + "'+'";
            }
          case 47: break;
          case 7: 
            { return yytext() + " line " + yyline + " cols " + yycolumn + " is " + "'-'";
            }
          case 48: break;
          case 8: 
            { return "*** Error linea " + yyline + " identificador inválido ";
            }
          case 49: break;
          case 9: 
            { token = yytext();
    fixed = yycolumn + token.length() - 2;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed + " is string variable";
            }
          case 50: break;
          case 10: 
            { return yytext() + " papu";
            }
          case 51: break;
          case 11: 
            { token = yytext();
    fixed = yycolumn + token.length() - 2;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed + " is identifier";
            }
          case 52: break;
          case 12: 
            { fixed = yycolumn + 1;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed + " is if";
            }
          case 53: break;
          case 13: 
            { token = yytext();
    fixed = yycolumn + 1;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed +  " is " + "'" + token + "'";
            }
          case 54: break;
          case 14: 
            { token = yytext();
    fixed = yycolumn + 1;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed + " is " + "'" + token + "'";
            }
          case 55: break;
          case 15: 
            { fixed = yycolumn + 1;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed + " is " + "'||'";
            }
          case 56: break;
          case 16: 
            { token = yytext();
    fixed = token.length() - 1;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed + " is hexadecimal";
            }
          case 57: break;
          case 17: 
            { token = yytext();
    fixed = yycolumn + token.length() - 1;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed + " is float (value = " + token + ")";
            }
          case 58: break;
          case 18: 
            { return "*** Error linea " + yyline + " identificador muy largo ";
            }
          case 59: break;
          case 19: 
            { fixed = yycolumn + 2;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed + " is int";
            }
          case 60: break;
          case 20: 
            { fixed = yycolumn + 2;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed + " is for";
            }
          case 61: break;
          case 21: 
            { fixed = yycolumn + 2;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed + " is New";
            }
          case 62: break;
          case 22: 
            { fixed = yycolumn + 1;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed + " is " + "'[]'";
            }
          case 63: break;
          case 23: 
            { fixed = yycolumn + 1;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed + " is " + "'{}'";
            }
          case 64: break;
          case 24: 
            { fixed = yycolumn + 1;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed + " is " + "'()'";
            }
          case 65: break;
          case 25: 
            { return yytext() + " multilinea papu";
            }
          case 66: break;
          case 26: 
            { fixed = yycolumn + 3;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed + " is null";
            }
          case 67: break;
          case 27: 
            { fixed = yycolumn + 3;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed + " is boolConstant (value = true)";
            }
          case 68: break;
          case 28: 
            { fixed = yycolumn + 3;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed + " is this";
            }
          case 69: break;
          case 29: 
            { fixed = yycolumn + 3;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed + " is void";
            }
          case 70: break;
          case 30: 
            { fixed = yycolumn + 4;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed + " is break";
            }
          case 71: break;
          case 31: 
            { fixed = yycolumn + 4;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed + " is class";
            }
          case 72: break;
          case 32: 
            { fixed = yycolumn + 4;
     return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed + " is boolConstant (value = false)";
            }
          case 73: break;
          case 33: 
            { fixed = yycolumn + 4;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed + " is while";
            }
          case 74: break;
          case 34: 
            { fixed = yycolumn + 5;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed + " is double";
            }
          case 75: break;
          case 35: 
            { fixed = yycolumn + 5;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed + " is string";
            }
          case 76: break;
          case 36: 
            { fixed = yycolumn + 6;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed + " is extends";
            }
          case 77: break;
          case 37: 
            { fixed = yycolumn + 8;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed + " is interface";
            }
          case 78: break;
          case 38: 
            { fixed = yycolumn + 3;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed + " is else";
            }
          case 79: break;
          case 39: 
            { fixed = yycolumn + 9;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed + " is implements";
            }
          case 80: break;
          case 40: 
            { fixed = yycolumn + 5;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed + " is return";
            }
          case 81: break;
          case 41: 
            { fixed = yycolumn + 7;
    return yytext() + " line " + yyline + " cols " + yycolumn + "-" + fixed + " is NewArray";
            }
          case 82: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
